@echo off
cd /d "c:\Users\tushar\Desktop\tushar-portfolio-fixed\tushhh"
echo Initializing git repository...
git init
echo Adding all files...
git add .
echo Committing files...
git commit -m "Initial commit: Modern portfolio with AI trading models"
echo Renaming branch to main...
git branch -M main
echo Adding remote origin...
git remote add origin https://github.com/TUSHARXP-10/universe-.git
echo Pushing to main branch...
git push -u origin main
echo Done! Your portfolio has been pushed to GitHub.
pause